services:
  db:
    image: postgres:14-alpine
    container_name: db
    hostname: db
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - netbot
    volumes:
      - db:/var/lib/postgresql/data 

  bot: 
    container_name: bot
    hostname: bot
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      BOT_TOKEN: ${BOT_TOKEN}
    ports:
      - 5678:5678
    build:
      context: "./bot"
    networks:
      - netbot
    depends_on:
      - db

networks:
  netbot:
    driver: bridge

volumes:
  db: {}
